# Multi-Environment Configuration
# Environment-specific settings for dev, staging, and production

environments:
  development:
    name: "Development"
    shortName: "dev"
    description: "Development environment for testing and experimentation"
    
    # Resource Configuration
    resourceConfig:
      allowedLocations: ["eastus2", "centralus"]
      allowedVMSizes: ["Standard_B1s", "Standard_B2s", "Standard_D2s_v3"]
      maxResourceGroupCount: 50
      maxSubscriptionCount: 5
      
    # Policy Configuration
    policyConfig:
      enforcementMode: "DoNotEnforce"  # Relaxed for development
      requiredTags: ["Environment", "Owner", "Project"]
      tagPatterns:
        Environment: "^dev$"
        Owner: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
        Project: "^[a-zA-Z0-9-]{3,50}$"
    

      
    # Security Configuration
    securityConfig:
      requireHttpsOnly: true
      enableDefenderForCloud: false
      logRetentionDays: 30
      
    # Networking
    networkConfig:
      allowedIPRanges: ["10.10.0.0/16"]
      enablePrivateEndpoints: false
      requireNetworkSecurityGroups: true
      
  staging:
    name: "Staging"
    shortName: "stg"
    description: "Staging environment for pre-production testing"
    
    # Resource Configuration
    resourceConfig:
      allowedLocations: ["eastus2", "centralus", "westus2"]
      allowedVMSizes: ["Standard_B2s", "Standard_D2s_v3", "Standard_D4s_v3"]
      maxResourceGroupCount: 25
      maxSubscriptionCount: 3
      
    # Policy Configuration
    policyConfig:
      enforcementMode: "Default"
      requiredTags: ["Environment", "CostCenter", "Owner", "Project"]
      tagPatterns:
        Environment: "^(staging|stg)$"
        CostCenter: "^CC-[0-9]{4}$"
        Owner: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
        Project: "^[a-zA-Z0-9-]{3,50}$"
    

      
    # Security Configuration
    securityConfig:
      requireHttpsOnly: true
      enableDefenderForCloud: true
      logRetentionDays: 90
      
    # Networking
    networkConfig:
      allowedIPRanges: ["10.20.0.0/16"]
      enablePrivateEndpoints: true
      requireNetworkSecurityGroups: true
      
  production:
    name: "Production"
    shortName: "prod"
    description: "Production environment with strict governance"
    
    # Resource Configuration
    resourceConfig:
      allowedLocations: ["eastus2", "centralus", "westus2"]
      allowedVMSizes: ["Standard_D2s_v3", "Standard_D4s_v3", "Standard_D8s_v3", "Standard_E4s_v3"]
      maxResourceGroupCount: 100
      maxSubscriptionCount: 10
      
    # Policy Configuration
    policyConfig:
      enforcementMode: "Default"
      requiredTags: ["Environment", "CostCenter", "Owner", "Project", "BusinessUnit", "Application"]
      tagPatterns:
        Environment: "^(production|prod)$"
        CostCenter: "^CC-[0-9]{4}$"
        Owner: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
        Project: "^[a-zA-Z0-9-]{3,50}$"
        BusinessUnit: "^(engineering|marketing|sales|operations)$"
        Application: "^[a-zA-Z0-9-]{3,50}$"
    

      
    # Security Configuration
    securityConfig:
      requireHttpsOnly: true
      enableDefenderForCloud: true
      logRetentionDays: 365
      requirePrivateEndpoints: true
      
    # Networking
    networkConfig:
      allowedIPRanges: ["10.30.0.0/16"]
      enablePrivateEndpoints: true
      requireNetworkSecurityGroups: true
      enableDDoSProtection: true

# Tenant Configuration
tenants:
  primary:
    tenantId: "00000000-0000-0000-0000-000000000000"  # Replace with actual tenant ID
    displayName: "Primary Tenant"
    domain: "company.com"
    managementGroups:
      root: "mg-root"
      platform: "mg-platform"
      landingZones: "mg-landing-zones"
      
  subsidiary:
    tenantId: "11111111-1111-1111-1111-111111111111"  # Replace with actual tenant ID
    displayName: "Subsidiary Tenant"
    domain: "subsidiary.com"
    managementGroups:
      root: "mg-subsidiary-root"
      platform: "mg-subsidiary-platform"
      landingZones: "mg-subsidiary-landing-zones"

# Global Settings
globalSettings:
  namingConvention:
    resourceGroupPrefix: "rg"
    storageAccountPrefix: "st"
    keyVaultPrefix: "kv"
    logAnalyticsPrefix: "log"
    separator: "-"
    
  complianceFrameworks:
    - "Azure Security Benchmark"
    - "ISO 27001:2013"
    - "SOC 2 Type II"
    
  defaultTags:
    ManagedBy: "Azure Governance Framework"
    Framework: "Enterprise Scale"
    Version: "2.0.0"